#!/usr/bin/env bash
# Summary: Install specified HashiCorp product at given version
# Usage: hashi-env install <product> [<version>]

source "$(dirname -- ${BASH_SOURCE[0]})/../env.sh"

set -euo pipefail

if [ -n "${HASHIENV_DEBUG:-}" ]; then
  set -x
fi

# Provide hashi-env completions
grep_args=()
beta=
alpha=
rc=
for arg; do
  case "$arg" in
  --complete )
    printf '%s\n' '--complete'
    # All of the options for products
    printf '%s\n' "${products[@]}"
    exit
    ;;
  --alpha|--all )
    alpha=1
    beta=1
    rc=1
    shift
    ;;
  --beta )
    beta=1
    rc=1
    shift
    ;;
  --rc )
    rc=1
    shift
    ;;
  --help|-h )
    hashi-env-help install >&2
    exit
    ;;
  esac
done

if [ -z "$alpha" ]; then
  grep_args=("${grep_args[@]}" -e '-alpha')
fi
if [ -z "$beta" ]; then
  grep_args=("${grep_args[@]}" -e '-beta')
fi
if [ -z "$rc" ]; then
  grep_args=("${grep_args[@]}" -e '-rc')
fi

if [ $# -gt 0 ]; then
  product="$1"; shift
  if [ $# -gt 0 ]; then
    version="${1}"; shift
  elif [ "${#grep_args[@]}" -lt 1 ]; then
    version="$(list-remote-versions "$product" "$version" | tail -n1)"
  else
    version="$(list-remote-versions "$product" "$version" | grep -v "${grep_args[@]}")"
  fi

  install-product "$product" "$version"
  hashi-env rehash
else
  hashi-env-help --usage install >&2
  exit 1
fi
