#!/usr/bin/env bash
# Summary: Configure the shell environment for hashi-env
# Usage: eval "$(hashi-env init - [--no-rehash] [<shell>])"

set -e
if [ -n "${HASHIENV_DEBUG:-}" ]; then
  set -x
fi

if [ "$1" = "--complete" ]; then
  echo -
  echo --no-rehash
  echo bash
  echo fish
  echo ksh
  echo zsh
  exit
fi

print=""
no_rehash=""

for args in "$@"; do
  if [ "$args" = '-' ]; then
    print=1
    shift
  fi

  if [ "$args" = '--no-rehash' ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps -p "$PPID" -o 'args=' 2>/dev/null || true)"
  shell="${shell%% *}"
  shell="${shell##-}"
  shell="${shell:-$SHELL}"
  shell="${shell##*/}"
fi

root="${0%/*}/.."

if [ -z "$print" ]; then
  case "$shell" in
    bash )
      if [ -f "${HOME}/.bashrc" ] && [ ! -f "${HOME}/.bash_profile" ]; then
        profile='~/.bashrc'
      else
        profile='~/.bash_profile'
      fi
      ;;
    zsh )
      profile='~/.zshrc'
      ;;
    ksh )
      profile='~/.profile'
      ;;
    fish )
      profile='~/.config/fish/config.fish'
      ;;
    * )
      profile='your profile'
      ;;
  esac

  { echo "# Load hashi-env automatically by appending"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and source (hashi-env init -|psub)'
      ;;
    * )
      printf 'export PATH="%s:$PATH"\n' "${HASHIENV_ROOT}/bin"
      echo 'if command -v hashi-env 1>/dev/null 2>&1; then eval "$(hashi-env init -)"; fi'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

case "$shell" in
  fish )
    echo "set -gx HASHIENV_SHELL '$shell'"
    ;;
  * )
    echo "export HASHIENV_SHELL='$shell'"
    ;;
esac

completion="${root}/completions/hashi-env.${shell}"
if [ -r "$completion" ]; then
  echo "source '$completion'"
fi

if [ -z "$no_rehash" ]; then
  echo 'command hashi-env rehash 2>/dev/null'
fi

commands=($(hashi-env-commands --sh))
case "$shell" in
  fish )
    cat <<EOS
function hashi-env
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    source (hashi-env "sh-\$command" \$argv|psub)
  case '*'
    command hashi-env "\$command" \$argv
  end
end
EOS
    ;;
  ksh )
    cat <<EOS
function hashi-env {
  typeset command
EOS
    ;;
  * )
    cat <<EOS
hashi-env() {
  local command
EOS
    ;;
esac

if [ "$shell" != "fish" ]; then
  IFS="|"
  cat <<EOS
  command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(hashi-env "sh-\$command" "\$@")";;
  *)
    command hashi-env "\$command" "\$@";;
  esac
}
EOS
fi
