#!/usr/bin/env bash
set -euo pipefail
# Summary: List all available hashi-env commands
# Usage: hashi-env commands [--sh|--no-sh]

if [ -z "${VERSION:-}" ]; then
	VERSION="$(command git -C "${HASHIENV_ROOT}" describe --tags --long 2>/dev/null || true)"
fi
if [ -z "${VERSION:-}" ]; then
	VERSION="$(command git -C "${HASHIENV_ROOT}" rev-parse --short HEAD 2>/dev/null | xargs -I{} echo "master-{}" || true)"
fi

printf '%s\n' "$VERSION"
