#!/usr/bin/env bash

source "$(dirname -- ${BASH_SOURCE[0]})/../env.sh"

current_version() {
	local -r product="$1"
	local -r global_version_file="${HASHIENV_ROOT}/version"
	local version=''

	: ${version:=$(env-version "${product}")}
	: ${version:=$(local-version "${product}")}
	: ${version:=$(global-version "${product}")}

	if [ -z "${version}" ]; then
		log-error "No version of ${product} is set. Perhaps set a default version globally in $(user-rel-path "$(expand-path "$global_version_file")") as \`${product} <version>'?"
		return 1
	fi
	printf '%s\n' "$version"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	set -euo pipefail

	current_version "$@"
fi
