#!/usr/bin/env bash

source "$(dirname -- ${BASH_SOURCE[0]})/../env.sh"

global_version() {
	local -r product="$1"
	local -r global_version_file="${HASHIENV_ROOT}/version"
	local version=''

	if [ -z "${version}" ] && [ -r "${global_version_file}" ]; then
		version=$(awk "/${product}/ { print \$2 }" "$global_version_file")
	fi
	if [ -z "${version}" ]; then
		return 1
	fi
	printf '%s\n' "$version"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	set -euo pipefail

	global_version "$@"
fi
